%% Generated by the Erlang ASN.1 compiler. Version: 5.3.1
%% Purpose: Erlang record definitions for each named and unnamed
%% SEQUENCE and SET, and macro definitions for each value
%% definition in module RoadWeatherMessage.

-ifndef(_ROADWEATHERMESSAGE_HRL_).
-define(_ROADWEATHERMESSAGE_HRL_, true).

-record('VehicleReport', {
  snapShot,
  wdmsFleetData = asn1_NOVALUE
  %% with extension mark
}).

-record('RoadWeatherDownload', {
  travelerData,
  wdmsFleetData = asn1_NOVALUE
  %% with extension mark
}).

-record('WDMSFleetData', {
  pavementTreat = asn1_NOVALUE,
  routingAdvice = asn1_NOVALUE
  %% with extension mark
}).

-record('NtcipPavementTreatment', {
  latitude,
  longitude,
  location,
  productType = asn1_NOVALUE,
  form = asn1_NOVALUE,
  percentage = asn1_NOVALUE,
  amount = asn1_NOVALUE,
  width = asn1_NOVALUE
  %% with extension mark
}).

-record('SnapShot', {
  thePosition,
  safetyExt = asn1_NOVALUE,
  dataSet = asn1_NOVALUE,
  %% with extensions
  weatherData = asn1_NOVALUE
}).

-record('NtcipEssData', {
  airTemp = asn1_NOVALUE,
  atmosphere = asn1_NOVALUE,
  wind = asn1_NOVALUE,
  humidity = asn1_NOVALUE,
  dewpoint = asn1_NOVALUE,
  pavement = asn1_NOVALUE,
  visibility = asn1_NOVALUE,
  visSituation = asn1_NOVALUE,
  cloudSitiation = asn1_NOVALUE,
  precipitation = asn1_NOVALUE,
  solarRadiation = asn1_NOVALUE
  %% with extension mark
}).

-record('NtcipAirTemperature', {
  temperature,
  measurementStdDev = asn1_NOVALUE,
  tempSensorHeight = asn1_NOVALUE
  %% with extension mark
}).

-record('NtcipAtmosphericPressure', {
  pressure,
  measurementStdDev = asn1_NOVALUE
  %% with extension mark
}).

-record('NtcipWind', {
  avgSpeed = asn1_NOVALUE,
  avgDirection = asn1_NOVALUE,
  currentSpeed = asn1_NOVALUE,
  curDirection = asn1_NOVALUE,
  gustSpeed = asn1_NOVALUE,
  gustDirection = asn1_NOVALUE
  %% with extension mark
}).

-record('NtcipRelativeHumidity', {
  relHumidity,
  source = asn1_NOVALUE
  %% with extension mark
}).

-record('NtcipDewPoint', {
  dewTemp,
  source = asn1_NOVALUE,
  measurementStdDev = asn1_NOVALUE
  %% with extension mark
}).

-record('NtcipPavement', {
  surfaceTemp = asn1_NOVALUE,
  tempStdDev = asn1_NOVALUE,
  condition = asn1_NOVALUE,
  moistureDepth = asn1_NOVALUE,
  roadRoughness = asn1_NOVALUE
  %% with extension mark
}).

-record('NtcipVisibility', {
  visibility
  %% with extension mark
}).

-record('NtcipVisibilitySituation', {
  situation
  %% with extension mark
}).

-record('NtcipCloudSituation', {
  situation
  %% with extension mark
}).

-record('NtcipPrecipitation', {
  precipitation
  %% with extension mark
}).

-record('NtcipSolarRadiation', {
  solarRadiation,
  measurementPeriod
  %% with extension mark
}).

-endif. %% _ROADWEATHERMESSAGE_HRL_
