%% Generated by the Erlang ASN.1 compiler. Version: 5.3.1
%% Purpose: Erlang record definitions for each named and unnamed
%% SEQUENCE and SET, and macro definitions for each value
%% definition in module SPAT.

-ifndef(_SPAT_HRL_).
-define(_SPAT_HRL_, true).

-record('SPAT', {
  timeStamp = asn1_NOVALUE,
  name = asn1_NOVALUE,
  intersections,
  regional = asn1_NOVALUE
  %% with extension mark
}).

-record('SPAT_regional_SEQOF', {
  regionId,
  regExtValue
}).

-record('AdvisorySpeed', {
  type,
  speed = asn1_NOVALUE,
  confidence = asn1_NOVALUE,
  distance = asn1_NOVALUE,
  class = asn1_NOVALUE,
  regional = asn1_NOVALUE
  %% with extension mark
}).

-record('AdvisorySpeed_regional_SEQOF', {
  regionId,
  regExtValue
}).

-record('ConnectionManeuverAssist', {
  connectionID,
  queueLength = asn1_NOVALUE,
  availableStorageLength = asn1_NOVALUE,
  waitOnStop = asn1_NOVALUE,
  pedBicycleDetect = asn1_NOVALUE,
  regional = asn1_NOVALUE
  %% with extension mark
}).

-record('ConnectionManeuverAssist_regional_SEQOF', {
  regionId,
  regExtValue
}).

-record('IntersectionState', {
  name = asn1_NOVALUE,
  id,
  revision,
  status,
  moy = asn1_NOVALUE,
  timeStamp = asn1_NOVALUE,
  enabledLanes = asn1_NOVALUE,
  states,
  maneuverAssistList = asn1_NOVALUE,
  regional = asn1_NOVALUE,
  %% with extensions
  roadAuthorityID = asn1_NOVALUE
}).

-record('IntersectionState_regional_SEQOF', {
  regionId,
  regExtValue
}).

-record('MovementEvent', {
  eventState,
  timing = asn1_NOVALUE,
  speeds = asn1_NOVALUE,
  regional = asn1_NOVALUE
  %% with extension mark
}).

-record('MovementEvent_regional_SEQOF', {
  regionId,
  regExtValue
}).

-record('MovementState', {
  movementName = asn1_NOVALUE,
  signalGroup,
  'state-time-speed',
  maneuverAssistList = asn1_NOVALUE,
  regional = asn1_NOVALUE
  %% with extension mark
}).

-record('MovementState_regional_SEQOF', {
  regionId,
  regExtValue
}).

-record('TimeChangeDetails', {
  startTime = asn1_NOVALUE,
  minEndTime,
  maxEndTime = asn1_NOVALUE,
  likelyTime = asn1_NOVALUE,
  confidence = asn1_NOVALUE,
  nextTime = asn1_NOVALUE
}).

-endif. %% _SPAT_HRL_
