%% Generated by the Erlang ASN.1 compiler. Version: 5.3.1
%% Purpose: Erlang record definitions for each named and unnamed
%% SEQUENCE and SET, and macro definitions for each value
%% definition in module AddGrpC.

-ifndef(_ADDGRPC_HRL_).
-define(_ADDGRPC_HRL_, true).

-record('Altitude', {
  value,
  confidence
}).

-record('PrioritizationResponse', {
  stationID,
  priorState,
  signalGroup
  %% with extension mark
}).

-record('ConnectionManeuverAssist-addGrpC', {
  vehicleToLanePositions,
  rsuDistanceFromAnchor = asn1_NOVALUE
}).

-record('IntersectionState-addGrpC', {
  activePrioritizations = asn1_NOVALUE
  %% with extension mark
}).

-record('MapData-addGrpC', {
  signalHeadLocations = asn1_NOVALUE
  %% with extension mark
}).

-record('Position3D-addGrpC', {
  altitude
  %% with extension mark
}).

-record('RestrictionUserType-addGrpC', {
  emission = asn1_NOVALUE
  %% with extension mark
}).

-record('SignalHeadLocation', {
  node,
  signalGroupID
  %% with extension mark
}).

-record('VehicleToLanePosition', {
  stationID,
  laneID
  %% with extension mark
}).

-endif. %% _ADDGRPC_HRL_
