%% Generated by the Erlang ASN.1 compiler. Version: 5.3.1
%% Purpose: Erlang record definitions for each named and unnamed
%% SEQUENCE and SET, and macro definitions for each value
%% definition in module SignalRequestMessage.

-ifndef(_SIGNALREQUESTMESSAGE_HRL_).
-define(_SIGNALREQUESTMESSAGE_HRL_, true).

-record('SignalRequestMessage', {
  timeStamp = asn1_NOVALUE,
  second,
  sequenceNumber = asn1_NOVALUE,
  requests = asn1_NOVALUE,
  requestor,
  regional = asn1_NOVALUE
  %% with extension mark
}).

-record('SignalRequestMessage_regional_SEQOF', {
  regionId,
  regExtValue
}).

-record('RequestorDescription', {
  id,
  type = asn1_NOVALUE,
  position = asn1_NOVALUE,
  name = asn1_NOVALUE,
  routeName = asn1_NOVALUE,
  transitStatus = asn1_NOVALUE,
  transitOccupancy = asn1_NOVALUE,
  transitSchedule = asn1_NOVALUE,
  regional = asn1_NOVALUE
  %% with extension mark
}).

-record('RequestorDescription_regional_SEQOF', {
  regionId,
  regExtValue
}).

-record('RequestorPositionVector', {
  position,
  heading = asn1_NOVALUE,
  speed = asn1_NOVALUE
  %% with extension mark
}).

-record('SignalRequestPackage', {
  request,
  minute = asn1_NOVALUE,
  second = asn1_NOVALUE,
  duration = asn1_NOVALUE,
  regional = asn1_NOVALUE
  %% with extension mark
}).

-record('SignalRequestPackage_regional_SEQOF', {
  regionId,
  regExtValue
}).

-record('SignalRequest', {
  id,
  requestID,
  requestType,
  inBoundLane,
  outBoundLane = asn1_NOVALUE,
  regional = asn1_NOVALUE
  %% with extension mark
}).

-record('SignalRequest_regional_SEQOF', {
  regionId,
  regExtValue
}).

-endif. %% _SIGNALREQUESTMESSAGE_HRL_
