%% Generated by the Erlang ASN.1 compiler. Version: 5.3.1
%% Purpose: Erlang record definitions for each named and unnamed
%% SEQUENCE and SET, and macro definitions for each value
%% definition in module ITIS.

-ifndef(_ITIS_HRL_).
-define(_ITIS_HRL_, true).

-record('ITIScodesAndText_SEQOF', {
  item
}).

-endif. %% _ITIS_HRL_
