%% Generated by the Erlang ASN.1 compiler. Version: 5.3.1
%% Purpose: Erlang record definitions for each named and unnamed
%% SEQUENCE and SET, and macro definitions for each value
%% definition in module CooperativeControlMessage.

-ifndef(_COOPERATIVECONTROLMESSAGE_HRL_).
-define(_COOPERATIVECONTROLMESSAGE_HRL_, true).

-record('CCMPartIIcontent', {
  'partII-Id',
  'partII-Value'
}).

-record('CooperativeControlMessage', {
  coreData,
  partII = asn1_NOVALUE
  %% with extension mark
}).

-record('CooperativeControlMessage_partII_SEQOF', {
  'partII-Id',
  'partII-Value'
}).

-record('LightVehicleCCMExtensions', {
  longCntrlState,
  targetId = asn1_NOVALUE,
  accelForecast = asn1_NOVALUE,
  accelTimeConst = asn1_NOVALUE,
  seperationDist = asn1_NOVALUE,
  frontCutIn = asn1_NOVALUE
  %% with extension mark
}).

-record('HeavyTruckCCMExtensions', {
  longCntrlState,
  targetId = asn1_NOVALUE,
  roadGrade = asn1_NOVALUE,
  brakePedalPos = asn1_NOVALUE,
  accelPedalPos = asn1_NOVALUE,
  desiredSpeed = asn1_NOVALUE,
  desiredAccel = asn1_NOVALUE,
  desiredTorque = asn1_NOVALUE,
  desiredTmRetarderTorque = asn1_NOVALUE,
  desiredEngRetarderTorque = asn1_NOVALUE,
  axesMvmt = asn1_NOVALUE,
  separationDist = asn1_NOVALUE,
  totalMass = asn1_NOVALUE,
  maxAvailAccel = asn1_NOVALUE,
  maxAvailDecel = asn1_NOVALUE,
  ccmFaultMode = asn1_NOVALUE,
  maneuverID = asn1_NOVALUE,
  frontCutIn = asn1_NOVALUE
  %% with extension mark
}).

-record('AccelTimeConstant', {
  accelTimeConst = asn1_NOVALUE,
  decelTimeConst = asn1_NOVALUE
}).

-record('AxesMovement', {
  yaw = asn1_NOVALUE,
  pitch = asn1_NOVALUE,
  roll = asn1_NOVALUE,
  yawRate = asn1_NOVALUE,
  pitchRate = asn1_NOVALUE,
  rollRate = asn1_NOVALUE
}).

-define('vehicleSafetyExt', 0).
-define('lightVehicleCCMExt', 1).
-define('heavyTruckCCMExt', 2).
-endif. %% _COOPERATIVECONTROLMESSAGE_HRL_
