%% Generated by the Erlang ASN.1 compiler. Version: 5.3.1
%% Purpose: Erlang record definitions for each named and unnamed
%% SEQUENCE and SET, and macro definitions for each value
%% definition in module J2540ITIS.

-ifndef(_J2540ITIS_HRL_).
-define(_J2540ITIS_HRL_, true).

-record('ITIScodesAndText_SEQOF', {
  item
}).

-endif. %% _J2540ITIS_HRL_
