%% Generated by the Erlang ASN.1 compiler. Version: 5.3.1
%% Purpose: Erlang record definitions for each named and unnamed
%% SEQUENCE and SET, and macro definitions for each value
%% definition in module RoadSafetyMessage.

-ifndef(_ROADSAFETYMESSAGE_HRL_).
-define(_ROADSAFETYMESSAGE_HRL_, true).

-record('RoadSafetyMessage', {
  commonContainer,
  content
  %% with extension mark
}).

-record('CommonContainer', {
  eventInfo,
  regionInfo,
  crossLinking = asn1_NOVALUE
  %% with extension mark
}).

-record('CurveContainer', {
  advisorySpeed,
  surfaceCondition = asn1_NOVALUE,
  minRadius = asn1_NOVALUE,
  bankAngle = asn1_NOVALUE,
  curveRegion = asn1_NOVALUE
  %% with extension mark
}).

-record('DynamicInfoContainer', {
  priority,
  dmsSignString,
  applicableRegion
  %% with extension mark
}).

-record('IncidentsContainer', {
  responderType = asn1_NOVALUE,
  incidentLocation
  %% with extension mark
}).

-record('LaneClosureContainer', {
  laneStatus = asn1_NOVALUE,
  laneStatusVaries = asn1_NOVALUE,
  closureRegion
  %% with extension mark
}).

-record('ReducedSpeedZoneContainer', {
  speedLimit,
  rszRegion
  %% with extension mark
}).

-record('SituationalContainer', {
  obstructions = asn1_NOVALUE,
  visibility = asn1_NOVALUE,
  peoplePresent = asn1_NOVALUE,
  anomalousTraffic = asn1_NOVALUE,
  applicableRegion
  %% with extension mark
}).

-record('ApplicableHeading', {
  heading,
  tolerance
  %% with extension mark
}).

-record('AudioLink', {
  amChannel = asn1_NOVALUE,
  fmChannel = asn1_NOVALUE,
  satelliteChannel = asn1_NOVALUE,
  urlChannel = asn1_NOVALUE
  %% with extension mark
}).

-record('BroadRegion', {
  applicableHeading,
  broadArea
  %% with extension mark
}).

-record('CrossLinking', {
  audioLinks = asn1_NOVALUE,
  visualLink = asn1_NOVALUE,
  rsmLink = asn1_NOVALUE
  %% with extension mark
}).

-record('EventIdentifier', {
  operatorID,
  uniqueID
  %% with extension mark
}).

-record('EventInfo', {
  eventID,
  eventUpdate,
  eventCancellation,
  startDateTime,
  endDateTime = asn1_NOVALUE,
  eventRecurrence = asn1_NOVALUE,
  causeCode,
  subCauseCode = asn1_NOVALUE,
  affectedVehicles = asn1_NOVALUE
  %% with extension mark
}).

-record('EventRecurrence', {
  startTime = asn1_NOVALUE,
  endTime = asn1_NOVALUE,
  startDate = asn1_NOVALUE,
  endDate = asn1_NOVALUE,
  monday,
  tuesday,
  wednesday,
  thursday,
  friday,
  saturday,
  sunday,
  exclusion = asn1_NOVALUE
  %% with extension mark
}).

-record('LaneInfo', {
  lanePosition,
  laneClosed,
  laneCloseOffset = asn1_NOVALUE
  %% with extension mark
}).

-record('Obstructions', {
  location,
  description = asn1_NOVALUE
  %% with extension mark
}).

-record('Offset3D', {
  'lat-offset',
  'long-offset',
  'elev-offset' = asn1_NOVALUE
  %% with extension mark
}).

-record('Path', {
  pathWidth,
  pathPoints
  %% with extension mark
}).

-record('RegionInfo', {
  referencePoint,
  locationUncertainty = asn1_NOVALUE,
  referencePointType = asn1_NOVALUE,
  descriptiveName = asn1_NOVALUE,
  scale = asn1_NOVALUE,
  approachRegion = asn1_NOVALUE
  %% with extension mark
}).

-record('VisualLink', {
  urlLink = asn1_NOVALUE
  %% with extension mark
}).

-endif. %% _ROADSAFETYMESSAGE_HRL_
