%% Generated by the Erlang ASN.1 compiler. Version: 5.3.1
%% Purpose: Erlang record definitions for each named and unnamed
%% SEQUENCE and SET, and macro definitions for each value
%% definition in module TollUsageAckMessage.

-ifndef(_TOLLUSAGEACKMESSAGE_HRL_).
-define(_TOLLUSAGEACKMESSAGE_HRL_, true).

-record('TollUsageAckMessage', {
  tumAck,
  ackMaxAge
  %% with extension mark
}).

-record('TumAckHash', {
  signedTumHash = asn1_NOVALUE,
  tempId,
  tumSequenceNum
  %% with extension mark
}).

-endif. %% _TOLLUSAGEACKMESSAGE_HRL_
